export const ADD_RENDER_ITEM = 'ADD_RENDER_ITEM'
export const EDIT_RENDER_ITEM = 'EDIT_RENDER_ITEM'
export const ACTIVE_RENDER_ITEM = 'ACTIVE_RENDER_ITEM'
export const BLUR_RENDER_ITEM = 'BLUR_RENDER_ITEM'

export const EDIT_DRAG_MODULE = 'EDIT_DRAG_MODULE'
export const EDIT_DRAGING = 'EDIT_DRAGING'
export const EDIT_RENDER_DATA = 'EDIT_RENDER_DATA'
export const EDIT_RENDER_WH = 'EDIT_RENDER_WH'

export const EDIT_MODULE_DATA = 'EDIT_MODULE_DATA'
export const RESET_RENDER_STATE = 'RESET_RENDER_STATE'

export const ADD_RENDER_PASTE_ITEM = 'ADD_RENDER_PASTE_ITEM'

// callback
export const BACKUP_RENDER_ITEM = 'BACKUP_RENDER_ITEM'
export const RECALL_RENDER_ITEM = 'RECALL_RENDER_ITEM'
export const NEXT_RENDER_ITEM = 'NEXT_RENDER_ITEM'
export const INIT_RENDER_ITEM = 'INIT_RENDER_ITEM'

// base
export const EDIT_CONTEXTMENU = 'EDIT_CONTEXTMENU'
export const PUSH_COPYDATA = 'PUSH_COPYDATA'
export const BLUR_COPYDATA = 'BLUR_COPYDATA'
